spring:
  data:
    redis:
      host: 192.168.213.134
      port: 6379
      database: 0
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
server:
  port: 8093
knife4j:
  basic:
    enable: true
xht:
  name: xht
  passwd: yzd12345
