spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.139:3306/learning?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021
  data:
    redis:
      host: 192.168.213.139
      port: 6379
      database: 0
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
      password: yzd2021
#      password: 111111
#      cluster:
#        nodes: 192.168.213.140:6381,192.168.213.140:6382,192.168.213.141:6383,192.168.213.141:6384,192.168.213.142:6385,192.168.213.142:6386
server:
  port: 8093
knife4j:
  basic:
    enable: true
xht:
  name: xht
  passwd: yzd12345
