server:
  port: 8098

spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 192.168.213.134
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      direct:
        acknowledge-mode: manual #手动确认消息被消费