server:
  port: 8092

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.139:3306/xht_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 192.168.213.139
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      direct:
        acknowledge-mode: manual #手动确认消息被消费